# Generated by Django 5.2.4 on 2025-07-13 22:47

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_userpagedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='website_code',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
