# Generated by Django 5.2.4 on 2025-07-13 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_user_website_code'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
