# Generated by Django 5.2.4 on 2025-07-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpagedata',
            name='content_as_string',
            field=models.TextField(default=''),
        ),
    ]
