# Generated by Django 5.2.4 on 2025-07-24 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0007_userpagedata_content_as_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpagedata',
            name='id',
        ),
        migrations.AddField(
            model_name='userpagedata',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
